### ISSUE TITLE
depswriter.py does not work with Python 3

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jooking/closure-library#450]
```

What steps will reproduce the problem?
1. Download Python 3.2.3: 
http://www.python.org/ftp/python/3.2.3/python-3.2.3.amd64.msi
2. Execute depswriter.py with --root-with-prefix switch:

[closure-lib]\closure/bin/build/depswriter.py --root_with_prefix="src ../src"

What is the expected output? What do you see instead?

Expected: Successful execution of script (as seen in Python 2.7)

Outcome: 
"'dict_keys' object has no attribute 'sort'"

What version of the product are you using? On what operating system?

- closure-library-20111110-r1376
- Windows 7
- Python 3.2.3


Please provide any additional information below.

I can confirm that depswriter.py works in Python 2.7. This may be a simple case 
of Python 3 being unsupported, in which case the Closure docs do not specify 
the version of Python required.
```

Original issue reported on code.google.com by `seanhodg...@googlemail.com` on 13 Apr 2012 at 8:13
